### ISSUE TITLE
Mod doesn't work any more

### ISSUE THREAD

**Issue by programmersockson** [Brybry16/BetterPolus#10]
Hello!

Mod is not compatible with the version v2023.6.27.
But it works with v2023.3.28.

Could you fix it?

**Comment by Tommy-XL** [comment]
The mod works fine with version 6.27, maybe you have an old version of BepinEx (Currently the latest 670)

**Comment by Brybry16** [comment]
The All-in-one Pack was using an older version of BepInEx. I created another AIO Pack with an updated version of BIE, which works on most recent versions.

You can **[download it here](https://github.com/Brybry16/BetterPolus/releases/download/v1.2.0/BetterPolus_All-in-one-Pack-1.2.0be670.zip)**
