### ISSUE TITLE
Add compatibily for version 2021-6-30s

### ISSUE THREAD

**Issue by Edmondio** [Brybry16/BetterPolus#7]
Is it possible to have compatibility with the latest version of among us? 2021.6.30

**Comment by Brybry16** [comment]
Hi @Edmondio !
I created a new release of BetterPolus that adds compatibility with Among Us v2021.6.30.

You can find it here : [BetterPolus v1.1.3](https://github.com/Brybry16/BetterPolus/releases/tag/v1.1.3)

Thank you for using BetterPolus 😄
