### ISSUE TITLE
This works on 2022.3.29s

### ISSUE THREAD

**Issue by Scoooom** [Brybry16/BetterPolus#8]
Can you please compile and upload a release? I've done so in a fork but this is where people end up googling for betterpolus

**Comment by Brybry16** [comment]
The mod works on the latest version of Among Us, I don't really think it is necessary to create a new release.

I edited the last release to include that it still works with the latest version of the game and can maybe change the readme file to add that as well but I don't really see the point to create a new release.

I'm currently working to add some options to the mod so there will be a new release sooner or later anyway
