### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by Kakshii** [Brybry16/BetterPolus#9]
ok so recently I found this mod and decided to try it with a pirated version of Among Us and it didn't work. So now I want to buy Among Us to play this mod as well as Submerged and now I'm wondering if the mod still works on the latest version of Among Us.

**Comment by Tommy-XL** [comment]
Yes, it works, the new Among Us update very rarely breaks this mod, and if it does, the developer makes it work again

**Comment by Tommy-XL** [comment]
And Submerged does not currently support the latest versions of Among Us

**Comment by Kakshii** [comment]
ah ok thank you
